- name: Setup prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Create github-runner user
  ansible.builtin.user:
    name: github

- name: make github action folder
  ansible.builtin.file:
    path: /actions-runner
    owner: github
    group: github
    state: directory

- name: Download github runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.332.0/actions-runner-linux-x64-2.332.0.tar.gz
    dest: /actions-runner
    owner: github
    group: github
    remote_src: yes

- name: Check github runner already exist or not
  ansible.builtin.stat:
    path: /actions-runner/.runner
  register: runner_stat

- name: Read token from vault
  set_fact:
    github_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=github-runner/data/path:token token=' ~ vault_token ~ ' url=http://vault.devopsmanju.shop:8200') }} --unattended"

- name: Create runner and start the configuration
  ansible.builtin.shell: ./config.sh --url https://github.com/manjudevopszone --token {{ github_token }}
  args:
    chdir: /actions-runner
  become_user: github
  when: not runner_stat.stat.exists

- name: Copy service file
  ansible.builtin.template:
    src: github-runner.service
    dest: /etc/systemd/system/github-runner/service

- name: Start github-runner service
  ansible.builtin.systemd:
    name: github-runner
    state: started
    enabled: yes
    daemon-reload: yes


#- name: Configure github runner
#  ansible.builtin.shell: ./config.sh --url https://github.com/manjudevopszone --token {{ lookup('community.hashi_vault.hashi_vault', 'secret=github-runner/data/path:RUNNER_TOKEN token=' ~ vault_token ~ ' url=http://vault.devopsmanju.shop:8200') }} --unattended
#  args:
#    chdir:  /actions-runner
#  become_user: github
#  when: not runner_stat.stat.exists

#- name: Get GitHub runner token
#  uri:
#    url: https://api.github.com/repos/manjudevopszone/tool-setup-code-2025/actions/runners/registration-token
#    method: POST
#    headers:
#      Authorization: "token {{ github_pat }}"
#      Accept: application/vnd.github+json
#  register: runner_token
#
#- name: Configure GitHub runner
#  shell: ./config.sh --url https://github.com/manjudevopszone/tool-setup-code-2025 --token {{ runner_token.json.token }}
#  args:
#    chdir: /actions-runner
#  become_user: github