- name: Setup prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Create github-runner user
  ansible.builtin.user:
    name: github

- name: make github action folder
  ansible.builtin.file:
    path: /actions-runner
    owner: github
    group: github
    state: directory

- name: Download github runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.332.0/actions-runner-linux-x64-2.332.0.tar.gz
    dest: /actions-runner
    owner: github
    group: github
    remote_src: yes

- name: Read token from vault
  set_fact:
    github_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=github-runner/data/path token=' ~ vault_token ~ ' url=http://vault.devopsmanju.shop:8200').token }}"

- name: Create runner and start the configuration
  ansible.builtin.debug:
    msg: ./config.sh --url https://github.com/manjudevopszone --token {{ github_token }}